title: "Ramiro Estrella Pernetti"
description: "Tecnico de redes | Portafolio Profesional"
baseurl: "" 
url: "https://proxmy.github.io" # IMPORTANTE: Pon tu URL real aqu√≠
theme: minima
plugins:
  - jekyll-feed
